SET (CPM_DOWNLOAD_VERSION 0.36.0)

IF (CPM_SOURCE_CACHE)
    SET (CPM_DOWNLOAD_LOCATION
         "${CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
ELSEIF (DEFINED ENV{CPM_SOURCE_CACHE})
    SET (CPM_DOWNLOAD_LOCATION
         "$ENV{CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
ELSE ()
    SET (CPM_DOWNLOAD_LOCATION
         "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
ENDIF ()

GET_FILENAME_COMPONENT (CPM_DOWNLOAD_LOCATION ${CPM_DOWNLOAD_LOCATION} ABSOLUTE)
IF (NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
    MESSAGE (STATUS "Downloading CPM.cmake to ${CPM_DOWNLOAD_LOCATION}")
    FILE (
        DOWNLOAD
        https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake
        ${CPM_DOWNLOAD_LOCATION})
ENDIF ()

INCLUDE (${CPM_DOWNLOAD_LOCATION})
